name: "❓ Question"
description: Ask a question about CalcMyPrint
title: "[Question]: "
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please describe your question in detail.
    validations:
      required: true
